version: "2"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    tenrest:
        build: .
        volumes:
           - .:/code
        ports:
            - "8080:8080"
        links:
            - redis
